version: 2.1
jobs:
  node:
    working_directory: ~/Avoid-Kuvid/
    docker:
      - image: cimg/node:12.16

    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: cd ~/Avoid-Kuvid/app/ && yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: jest tests
          command: |
            cd ~/Avoid-Kuvid/app/
            mkdir -p test-results/jest
            yarn run test
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml
            JEST_JUNIT_OUTPUT_NAME: test-results/jest/junit.xml

      - persist_to_workspace:
          root: ~/Avoid-Kuvid/app/
          paths:
            - node_modules

      - store_test_results:
          path: ~/Avoid-Kuvid/app/test-results

      - store_artifacts:
          path: ~/Avoid-Kuvid/app/test-results


workflows:
  avoid-kuvid:
    jobs:
      - node
